const TOPICS = [
    "Trending",
    "India",
    "World",
    "Sports",
    "Tech",
    "Business",
    "Science",
    "Entertainment",
]

const DEFAULT_TOPIC = "Trending";

const CITIES = [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Ahemdabad",
    "Allahabad",
    "Bhubaneswar",
    "Coimbatore",
    "Gurgaon",
    "Guwahati",
    "Hubli",
    "Kanpur",
    "Kolkata",
    "Ludhiana",
    "Mangalore",
    "Mysore",
    "Noida",
    "Pune",
    "Goa",
    "Chandigarh",
    "Lucknow",
    "Patna",
    "Jaipur",
    "Nagpur",
    "Rajkot",
    "Ranchi",
    "Surat",
    "Vadodara",
    "Varanasi",
    "Thane",
    "Thiruvananthapuram"
]

const TOPIC_PROVIDERS = {
    "Trending": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    "India": "http://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms",
    "World": "http://timesofindia.indiatimes.com/rssfeeds/296589292.cms",
    "Sports": "http://timesofindia.indiatimes.com/rssfeeds/4719148.cms",
    "Tech": "http://timesofindia.indiatimes.com/rssfeeds/66949542.cms",
    "Business": "http://timesofindia.indiatimes.com/rssfeeds/1898055.cms",
    "Science": "http://timesofindia.indiatimes.com/rssfeeds/-2128672765.cms",
    "Entertainment": "http://timesofindia.indiatimes.com/rssfeeds/1081479906.cms",
    "Mumbai": "http://timesofindia.indiatimes.com/rssfeeds/-2128838597.cms",
    "Delhi": "http://timesofindia.indiatimes.com/rssfeeds/-2128839596.cms",
    "Bangalore": "http://timesofindia.indiatimes.com/rssfeeds/-2128833038.cms",
    "Hyderabad": "http://timesofindia.indiatimes.com/rssfeeds/-2128816011.cms",
    "Chennai": "http://timesofindia.indiatimes.com/rssfeeds/2950623.cms",
    "Ahemdabad": "http://timesofindia.indiatimes.com/rssfeeds/-2128821153.cms",
    "Allahabad": "http://timesofindia.indiatimes.com/rssfeeds/3947060.cms",
    "Bhubaneswar": "http://timesofindia.indiatimes.com/rssfeeds/4118235.cms",
    "Coimbatore": "http://timesofindia.indiatimes.com/rssfeeds/7503091.cms",
    "Gurgaon": "http://timesofindia.indiatimes.com/rssfeeds/6547154.cms",
    "Guwahati": "http://timesofindia.indiatimes.com/rssfeeds/4118215.cms",
    "Hubli": "http://timesofindia.indiatimes.com/rssfeeds/3942695.cms",
    "Kanpur": "http://timesofindia.indiatimes.com/rssfeeds/3947067.cms",
    "Kolkata": "http://timesofindia.indiatimes.com/rssfeeds/-2128830821.cms",
    "Ludhiana": "http://timesofindia.indiatimes.com/rssfeeds/3947051.cms",
    "Mangalore": "http://timesofindia.indiatimes.com/rssfeeds/3942690.cms",
    "Mysore": "http://timesofindia.indiatimes.com/rssfeeds/3942693.cms",
    "Noida": "http://timesofindia.indiatimes.com/rssfeeds/8021716.cms",
    "Pune": "http://timesofindia.indiatimes.com/rssfeeds/-2128821991.cms",
    "Goa": "http://timesofindia.indiatimes.com/rssfeeds/3012535.cms",
    "Chandigarh": "http://timesofindia.indiatimes.com/rssfeeds/-2128816762.cms",
    "Lucknow": "http://timesofindia.indiatimes.com/rssfeeds/-2128819658.cms",
    "Patna": "http://timesofindia.indiatimes.com/rssfeeds/-2128817995.cms",
    "Jaipur": "http://timesofindia.indiatimes.com/rssfeeds/3012544.cms",
    "Nagpur": "http://timesofindia.indiatimes.com/rssfeeds/442002.cms",
    "Rajkot": "http://timesofindia.indiatimes.com/rssfeeds/3942663.cms",
    "Ranchi": "http://timesofindia.indiatimes.com/rssfeeds/4118245.cms",
    "Surat": "http://timesofindia.indiatimes.com/rssfeeds/3942660.cms",
    "Vadodara": "http://timesofindia.indiatimes.com/rssfeeds/3942666.cms",
    "Varanasi": "http://timesofindia.indiatimes.com/rssfeeds/3947071.cms",
    "Thane": "http://timesofindia.indiatimes.com/rssfeeds/3831863.cms",
    "Thiruvananthapuram": "http://timesofindia.indiatimes.com/rssfeeds/878156304.cms"
}

const SUBSCRIBE_API = "http://localhost:4000/api/subscribe/"

module.exports = { TOPICS, DEFAULT_TOPIC, CITIES, TOPIC_PROVIDERS, SUBSCRIBE_API }